### ISSUE TITLE
Add importers

### ISSUE THREAD

**Issue by jsstevenson** [dgidb/dgidb-v5#36]
Big picture

- [ ] Consider swapping out any low-hanging TSV updaters for direct source or API imports
- [ ] Figure out what this is: https://raw.githubusercontent.com/dgidb/dgidb/source_tsvs/source_tsvs/TTD_INTERACTIONS.tsv

Specific sources

- [x] BaderLab
- [x] CancerCommons
- [x] Caris
- [x] CGI
- [x] Clearity Foundation Biomarkers
- [ ] Clearity Foundation Clinical Trial: Non-existent interaction claim type issue (immunotherapy) #49 
- [x] CiVIC
- [x] COSMIC
- [x] dGene
- [ ] DrugBank: Figure out data source, #52 
- [x] Docm
- [x] DTC
- [ ] Ensembl: #55 
- [ ] Entrez: #56 
- [x] FDA
- [x] Foundation One Genes
- [x] GO
- [ ] #57
- [x] Hingorini Casas
- [ ] Hopkins Groom: Add gene claim category "DNA DIRECTED DNA POLYMERASE" #49 
- [x] Human Protein Atlas
- [x] IDG: Could probably refactor as API importer. See #48 
- [ ] #54
- [x] MSK impact
- [ ] My Cancer Genome: Non-existent interaction claim type issue (immunotherapy) #49 
- [x] My Cancer Genome clinical trial
- [ ] NCI: #51 
- [x] OncoKB: #47 
- [x] Oncomine
- [x] PharmGKB
- [x] Pharos 
- [x] Russ-Lampel
- [x] TALC: #46 
- [x] Tdg
- [x] Tempus
- [x] Tend
- [x] TTD

**Comment by mcannon068nw** [comment]
IDG list focuses on understudied proteins to be illuminated and the list can change annually. IDG Y3 to Y4 resulted in removal of 9 genes and addition of 6 genes. 

Removed:
`[{'Gene': 'CDK11A', 'IDGFamily': 'Kinase'},
 {'Gene': 'CDK11B', 'IDGFamily': 'Kinase'},
 {'Gene': 'CDK16', 'IDGFamily': 'Kinase'},
 {'Gene': 'CDK17', 'IDGFamily': 'Kinase'},
 {'Gene': 'CDK18', 'IDGFamily': 'Kinase'},
 {'Gene': 'CDKL2', 'IDGFamily': 'Kinase'},
 {'Gene': 'ICK', 'IDGFamily': 'Kinase'},
 {'Gene': 'SGK494', 'IDGFamily': 'Kinase'},
 {'Gene': 'GPR68', 'IDGFamily': 'GPCR'}]`

Added:
`[{'Gene': 'CILK1', 'IDGFamily': 'Kinase'},
 {'Gene': 'RSKR', 'IDGFamily': 'Kinase'},
 {'Gene': 'CACNA1D', 'IDGFamily': 'IonChannel'}]`

Relationship between removed genes and IDGfamily should still be the same (i.e. CDK11A is still a Kinase) and still valuable. Append 3 new additions from Y4 to our list?

**Comment by mcannon068nw** [comment]
For TALC, citation is different in three places but 'most correct' citation appears to be from website:

Morgensztern D, Campo MJ, Dahlberg SE, Doebele RC, Garon E, Gerber DE, Goldberg SB, Hammerman PS, Heist RS, Hensing T, et al. Molecularly targeted therapies in non-small-cell lung cancer annual update 2014. J Thorac Oncol 2015; 10: S1-63. PMID: 25535693

Data from this source available in v4 repo ([source_tsvs pr](https://github.com/dgidb/dgidb/pull/588/files#diff-56adb1b4d02ad93d06ceeb65ddcc7014025390ef112d69aea88e7352a30d220c))

**Comment by mcannon068nw** [comment]
Chembl Importer has a number of interaction types that aren't recognized by database and likely need standardization to existing terms (i.e. ALLOSTERIC ANTAGONIST) or new entry types.

Full set of interaction types returned from chembl_30: `'ACTIVATOR',
 'AGONIST',
 'ALLOSTERIC ANTAGONIST',
 'ANTAGONIST',
 'ANTISENSE INHIBITOR',
 'BINDING AGENT',
 'BLOCKER',
 'CROSS-LINKING AGENT',
 'DEGRADER',
 'DISRUPTING AGENT',
 'HYDROLYTIC ENZYME',
 'INHIBITOR',
 'INVERSE AGONIST',
 'MODULATOR',
 'NEGATIVE ALLOSTERIC MODULATOR',
 'NEGATIVE MODULATOR',
 'OPENER',
 'OTHER',
 'PARTIAL AGONIST',
 'POSITIVE ALLOSTERIC MODULATOR',
 'POSITIVE MODULATOR',
 'PROTEOLYTIC ENZYME',
 'RELEASING AGENT',
 'STABILISER',
 'SUBSTRATE',
 'VACCINE ANTIGEN'`

**Comment by jsstevenson** [comment]
Closing this, remnant broken things should be handled as separate issues
